# Generated by Django 3.1.2 on 2020-11-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='pokedex/static/images/pokedex/')),
                ('element', models.CharField(blank=True, choices=[('leaf', 'Leaf'), ('water', 'Water'), ('fire', 'Fire')], max_length=100)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
